- name: Configure web servers
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: latest
    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /web/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Reload Nginx Service
      ansible.builtin.systemd_service:
        name: nginx.service
        state: reloaded
